import {
  LayoutDashboard,
  Users,
  Building2,
  Shield,
  Key,
  UserCheck,
  Handshake,
  FileText,
  BarChart3,
  FileInput,
  GraduationCap,
  Settings,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Target,
  Layers,
  Award,
  Network,
  FileSearch,
  UserPlus,
  UserCircle,
  ShieldCheck,
  LockKeyhole,
  Route,
  School,
  LayoutList,
  Database,
  Globe,
  Briefcase,
  SplitSquareVertical,
  CheckCircle,
  ScrollText,
  BookOpen,
  FolderOpen,
  ClipboardCheck,
} from 'lucide-react';

export const iconMap: Record<string, React.FC<any>> = {
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'user-circle': UserCircle,
  'shield-check': ShieldCheck,
  route: Route,
  'layout-list': LayoutList,
  'layout-dashboard': LayoutDashboard,
  users: Users,
  'graduation-cap': GraduationCap,
  building2: Building2,
  shield: Shield,
  'user-check': UserCheck,
  key: Key,
  settings: Settings,
  'file-text': FileText,
  target: Target,
  layers: Layers,
  award: Award,
  network: Network,
  'bar-chart3': BarChart3,
  database: Database,
  globe: Globe,
  handshake: Handshake,
  'file-input': FileInput,
  'user-plus': UserPlus,
  'file-search': FileSearch,
  school: School,
  briefcase: Briefcase,
  'lock-keyhole': LockKeyhole,
  'split-square-vertical': SplitSquareVertical,
  'check-circle': CheckCircle,
  'scroll-text': ScrollText,
  'book-open': BookOpen,
  'folder-open': FolderOpen,
  'clipboard-check':ClipboardCheck,
};

export function DynamicIcon({ name, ...props }: { name: string; [key: string]: any }) {
  const Icon = iconMap[name];
  return Icon ? <Icon {...props} /> : null;
}
